apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: somnia-bot-data
  namespace: somnia
  labels:
    app: somnia-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
